version: '3.3'

services:
  app:
    build: .
    environment:
      - PORT=3000
    networks:
      - internal
      - proxy

  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy
  
networks:
  internal:
  proxy:
